title: James' Blog
favicon: /icon.svg
icon: /icon.svg

menu:
  Articles: /archives
  About: /about

copyright: 2024 James Hsueh

# Latex setting
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
  plugins:
    - plugin:
        name: markdown-it-katex
        enable: true
  anchors:
    level: 1
    collisionSuffix: ''

